[options]
db_host = localhost
db_port = 5432
db_user = mavazi
db_password = safeway
db_name = mavazisafeway
addons_path = D:\DEV\mavazisafeway\addons
admin_passwd = $pbkdf2-sha512$600000$wPjf./9/T4lxjpGSshZibA$sLgWl/yVYEcjdlIm0T6/fyVcuQ7/AubZ7vvP2cHRqU8drAFg5wFpAGMdZKOs2Y1D4ogM2uuNRMRAJnnmLWM/fQ

