[options]
admin_passwd = Tusker01
db_host = localhost
db_port = 5432
db_user = odoo19
db_password = Tusker01
db_name = odoomvz
proxy_mode = True
addons_path = D:\Mavazi Enterprise\odoo\addons, D:\Mavazi Enterprise\custom-addons

